### ISSUE TITLE
Bug: Error trying to add a dashboard: unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec

### ISSUE THREAD

**Issue by camba1** [cdk8s-team/cdk8s-grafana#92]
### What happened:

Tried adding a dashboard to grafana in Python using:

```python
        grafana.add_dashboard("k8sDashBoard",
                              title="Kubernetes Metrics",
                              json_model=k8s_dashboard,
                              data_source_variables={"DS_PROMETHEUS": "prometheus.name"}
                              )
```

### Expected:

The dashboard gets added to Grafana

### Result:

cdk8s synth worked fine and generated the Yaml. However on kubectl apply, K8s threw the error:

> error: error validating "dist/GrafanaDashboard.grafana-k8sdashboard-c8f7fb82.k8s.yaml": error validating data: ValidationError(GrafanaDashboard.spec): unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec; if you choose to ignore these errors, turn validation off with --validate=false

### Reason for Issue:
The generated manifest added a spec.name field which is not recognized but the validation. Synth is adding the id fo the dashboard as a name inside the spec. Partial yaml naivest below (for brevity):

```yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  labels:
    app: grafana
  name: grafana-k8sdashboard2-c8bfb3a3
  namespace: my-grafana-operator
spec:
  datasources:
    - datasourceName: prometheus.name
      inputName: DS_PROMETHEUS
  json: <...>
  name: k8sDashBoard
  plugins: []
```

If the spec.name is commented out, the yaml can be deployed normally

 cdk8s synth --version
 1.0.57

### How to fix it

Change required to operator in cdk8s-grafana/src/dashboard.ts 

```typescript
    new GrafanaDashboard(this, 'Resource', {
      metadata: {
        labels: props.labels,
        namespace: props.namespace,
      },
      spec: {
        customFolderName: props.folder,
        datasources: dataSources,
        plugins: this.plugins,
        json: JSON.stringify({
          ...defaults,
          ...props.jsonModel,
        }, null, 2),
        name: id,
      },
    });
```
Should be:

```typescript
    new GrafanaDashboard(this, 'Resource', {
      metadata: {
        labels: props.labels,
        namespace: props.namespace,
      },
      spec: {
        customFolderName: props.folder,
        datasources: dataSources,
        plugins: this.plugins,
        json: JSON.stringify({
          ...defaults,
          ...props.jsonModel,
        }, null, 2),
      },
    });
```
